apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-generic
spec:
  params:
    - name: image
      type: string
      description: Image for step invoke-script
      default: ubuntu
  resources:
    inputs:
      - name: workspace
        type: git
  steps:
    - name: invoke-script
      image: $(params.image)
      script: |
        chmod -R +x ./workspace
        cd ./workspace
        ./main.sh