apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-generic
spec:
  resources:
    inputs:
      - name: workspace
        type: git
  steps:
    - name: readme
      image: ubuntu
      script: |
        cat workspace/ReadMe.md