apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-generic
spec:
  params:
    - name: image
      type: string
      description: Image for task generic
      default: ubuntu
  resources:
    - name: git-resource
      type: git
  tasks:
    - name: trigger-task-generic
      taskRef:
        name: task-generic
      resources:
        inputs:
          - name: workspace
            resource: git-resource
      params:
        - name: image
          value: $(params.image)