apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-run-generic
spec:
  params:
  - name: image
    value: mcr.microsoft.com/powershell
  pipelineRef:
    name: pipeline-generic
  resources:
  - name: git-resource
    resourceSpec:
      type: git
      params:
        - name: url
          value: https://github.com/haidouks/tekton-iac.git
  #- name: git-resource
  #  resourceRef:
  #    name: git-config-server